# Configuration for technote-space/auto-card-labeler (see for example .github/workflows/cards.yml)

Development:
    To do:
        - to do
    In progress:
        - in progress
    Ready for review:
        - ready for review
    Review in progress:
        - in review
    Reviewer approved:
        - approved
    Done:
        - done
