# GitPod Configuration (see https://www.gitpod.io/docs/config-gitpod-file)

tasks:
    - before: |
          if [ ! -e .env ]; then
              echo "AUTH_SECRET=\"$(openssl rand -base64 40)\"" > .env
              echo "DATABASE_URL=\"postgresql://postgres:postgres@localhost:5432/postgres\"" >> .env
              echo "MAGIC_KEY=\"pk_live_key\"" >> .env
              echo "MAGIC_SECRET=\"sk_live_secret\"" >> .env
          fi
          npm run up
      init: npm ci && npm run new
      command: npm run dev
ports:
    - port: 3000
      onOpen: open-preview
    - port: 5432
      onOpen: ignore
    - port: 8002
      onOpen: ignore
    - port: 9229
      onOpen: ignore

github:
    prebuilds:
        # enable for the default branch (defaults to true)
        master: true
        # enable for all branches in this repo (defaults to false)
        branches: false
        # enable for pull requests coming from this repo (defaults to true)
        pullRequests: true
        # enable for pull requests coming from forks (defaults to false)
        pullRequestsFromForks: false
        # add a check to pull requests (defaults to true)
        addCheck: prevent-merge-on-error # fail when the prebuild fails
        # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
        addComment: false
        # add a "Review in Gitpod" button to the pull request's description (defaults to false)
        addBadge: true
