name: Card moved

on:
    project_card:
    workflow_run:
        workflows:
            - Opened
            - Ready for review
        types:
            - completed

jobs:
    triage:
        name: Apply a label based on project card column
        runs-on: ubuntu-latest
        timeout-minutes: 10
        steps:
            - name: Run the auto-card-labeler action
              uses: technote-space/auto-card-labeler@v2
    state:
        name: Change state based on column
        runs-on: ubuntu-latest
        timeout-minutes: 10
        steps:
            - name: Run the issue-states action
              uses: dessant/issue-states@v2
              with:
                  open-issue-columns: To do, In progress, Ready for review, Review in progress, Reviewer approved
                  closed-issue-columns: Done
