name: CI

on: push

jobs:
    ci:
        strategy:
            matrix:
                node:
                    - 14
                    - 16
                    - 17
                runner:
                    - ubuntu-latest
                    - macos-latest
                    - windows-latest

        name: Continuous Integration (${{ matrix.runner }} / Node ${{ matrix.node }})
        runs-on: ${{ matrix.runner }}
        timeout-minutes: 30
        steps:
            - name: Git Checkout
              uses: actions/checkout@v3
            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node }}
                  cache: npm
            - name: Install dependencies
              run: npm ci
            - name: Run Tests
              run: npm run ci
              env:
                  ci: true
                  NODE_ENV: production
