name: CI

on: push

jobs:
    ci:
        strategy:
            matrix:
                node:
                    - 14
                    - 16
                    - 17
                runner:
                    - ubuntu-latest
                    - macos-latest
                    - windows-latest

        name: Continuous Integration (${{ matrix.runner }} / Node ${{ matrix.node }})
        runs-on: ${{ matrix.runner }}
        timeout-minutes: 30
        steps:
            - name: Git Checkout
              uses: actions/checkout@v3
            - name: Cache Next.js
              uses: actions/cache@v2
              with:
                  path: ${{ github.workspace }}/.next/cache
                  # Generate a new cache whenever packages or source files change.
                  key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
                  # If source files changed but packages didn't, rebuild from a prior cache.
                  restore-keys: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-
            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node }}
                  cache: npm
            - name: Install dependencies
              run: npm ci
            - name: Run Tests
              run: npm run ci
              env:
                  ci: true
                  NODE_ENV: production
