name: Draft

on:
    pull_request:
        types:
            - converted_to_draft
            - review_request_removed

jobs:
    move:
        name: Back to the drawing board
        runs-on: ubuntu-latest
        timeout-minutes: 10
        steps:
            - name: Move the card
              uses: alex-page/github-project-automation-plus@v0.8.1
              with:
                  project: Development
                  column: In progress
                  repo-token: ${{ secrets.WORKFLOW_TOKEN }}
