# This workflow deploys the PR to fly.io 🚀
name: Preview Deployment

on: pull_request

# Cancel previous instances of this workflow (per PR)
concurrency:
    group: preview-${{ github.event.number }}
    cancel-in-progress: true

env:
    FLY_API_TOKEN: "${{ secrets.FLY_API_TOKEN }}"
    APP_NAME: "lsg-pr-${{ github.event.number }}"
    APP_ORG: lsglab
    APP_REGION: fra
    APP_CLUSTER: lsg-pr-db

jobs:
    deploy-pr:
        name: PR Preview
        runs-on: ubuntu-latest
        concurrency: ${{ github.workflow }}
        timeout-minutes: 30
        environment:
            name: "Preview (PR #${{ github.event.number }})"
            url: "${{ steps.deploy.outputs.url }}"
        steps:
            - name: Checkout
              uses: actions/checkout@v3.0.0
            - name: Setup
              uses: superfly/flyctl-actions/setup-flyctl@master
            - name: Status Check
              run: |
                  if flyctl status --app "${{ env.APP_NAME }}"; then
                    echo "APP_EXISTS=true" >> $GITHUB_ENV
                    echo "✅ APP EXISTS"
                  else
                    echo "APP_EXISTS=false" >> $GITHUB_ENV
                    echo "⛔️ APP DOES NOT EXIST"
                  fi
            - name: Launch
              if: ${{ env.APP_EXISTS != 'true' }}
              run: |
                  flyctl launch --copy-config --name "${{ env.APP_NAME }}" --no-deploy --org "${{ env.APP_ORG }}" --region "${{ env.APP_REGION }}" --remote-only
                  flyctl postgres attach --app "${{ env.APP_NAME }}" --postgres-app "${{ env.APP_CLUSTER }}"
                  flyctl secrets set --app "${{ env.APP_NAME }}" AUTH_SECRET="$(openssl rand -base64 40)" MAGIC_KEY="${{ secrets.MAGIC_KEY }}" MAGIC_SECRET="${{ secrets.MAGIC_SECRET }}"
            - name: Deploy
              id: deploy
              run: |
                  exec 5>&1
                  DEPLOY_LOG=$((flyctl deploy --app "${{ env.APP_NAME }}" --now --remote-only --strategy immediate 2>&1 && echo '✅ DEPLOY SUCCESSFUL, following up with status checks... (#EC1)' || echo '❌ DEPLOY FAILED; Might be misleading error, checking... (#EC2)') | tee >(cat - >&5))
                  if echo "$DEPLOY_LOG" | grep -F '#EC2'; then
                    if echo "$DEPLOY_LOG" | grep -F 'No deployment available to monitor'; then
                        echo "🐛 Known bug, continuing..."
                        sleep 15
                    else
                        echo "🚨 The deployment failed. Check the logs above."
                        echo "💤 Logging out..."
                        flyctl auth logout
                        echo "✅ Logged out"
                        exit 1
                    fi
                  fi
                  flyctl status --app "${{ env.APP_NAME }}"
                  APP_STATUS=$(flyctl status --app "${{ env.APP_NAME }}" --json)
                  APP_HOSTNAME=$(printf '%s' "$APP_STATUS" | jq -r .Hostname)
                  printf '%s' "$APP_STATUS" | jq -r .Deployed | grep -F true
                  printf '%s' "$APP_STATUS" | jq -r .Status | grep -F running
                  echo "::set-output name=url::https://$APP_HOSTNAME"
                  echo "💤 Logging out..."
                  flyctl auth logout
                  echo "✅ Logged out"
