name: Reaction Comments

on:
    issue_comment:
        types:
            - created
            - edited
    pull_request_review_comment:
        types:
            - created
            - edited
    schedule:
        - cron: 0 0 * * *

jobs:
    reaction:
        name: Remove reaction comments
        runs-on: ubuntu-latest
        steps:
            - name: Run the reaction-comments action
              uses: dessant/reaction-comments@v2
