name: Reopened

on:
    pull_request:
        types:
            - reopened
    issues:
        types:
            - reopened

jobs:
    reboard:
        name: Do "Opened" checks again
        runs-on: ubuntu-latest
        timeout-minutes: 10
        steps:
            - name: Close if opened by non-stargazer
              uses: uhyo/please-star-first@master
